### ISSUE TITLE
Crash on opening article view on Android M

### ISSUE THREAD

**Issue by skolima** [travistabbal/GrazeRSS#24]
Opening any article after updating the phone to Android 6.0 will crash GrazeRSS.

I'll try to add a proper stack trace later - is anyone getting the error reports Android auto-uploads after a crash?

**Comment by travistabbal** [comment]
Thanks for the report. I haven't upgraded to 6 yet, but I'll investigate
it. If you can get a stack trace, it would help.

**Comment by skolima** [comment]
logcat output: https://gist.github.com/skolima/0cf080e0d32ea1a2fe3d

**Comment by travistabbal** [comment]
Fixed in 2.0.8.
