### ISSUE TITLE
Push 2.0.9 to Store

### ISSUE THREAD

**Issue by BenjaminHCCarr** [travistabbal/GrazeRSS#27]
Travis,
We've all been "testing" the state sync feature for a few months, I don't see errors reported. Can we push 2.0.9 to the Play Store, side loading is possible, but being able to just refer people to the store is nice, plus I have a device I can't sideload on.

Just a thought/request.
-Ben # @

**Comment by BenjaminHCCarr** [comment]
HI Travis,
Hope everything is going okay, any chance we can get 2.0.9 pushed to the play store, or is there some new google restriction ala apple no longer supporting IPv4 only apps?
-Ben

**Comment by travistabbal** [comment]
Ah yes, sorry about the delay on that. My build machine crashed and I'm
getting it going again. I do have the binary though, so I can push that to
the store. Just got distracted. :)

**Comment by BenjaminHCCarr** [comment]
Thanks so much @travistabbal I just keep moving the test distributed .apk from device to device. And with metering now it is handy!
